### ISSUE TITLE
Can't write to registers

### ISSUE THREAD

**Issue by Vitorbnc** [Helmuthn/ads8689_Arduino#2]
Hi!
Before anything else, great job! I was writing my own library when I found yours. I tested it with ESP32 and I am capable of reliably reading data.  I get a stream of 16 bits followed by 16 zeroes.
However, when I tried writing to the registers nothing happened in the output data:

`  adc->transmit(ADS8689_SET_HWORD,ADS8689_RANGE_SEL_REG,0b0100);
  adc->transmit(ADS8689_SET_HWORD,ADS8689_DATAOUT_CTL_REG,0xFFFF);`

The output value does not change, nor does any 1 appear after the conversion value. I'll try to take a look at MOSI with a logic analyzer later, but the connection seems fine. Did you test the write commands too?

**Comment by Vitorbnc** [comment]
Hi!
I was able to write to the registers and get results, tested with this:
`// Suggested test by TI engineer: To change the ADC's input range to +/-0.625*Vref, use the code D0 14 0004`
  `adc->transmit(ADS8689_WRITE_FULL,ADS8689_RANGE_SEL_REG,0x0004);`

  `//Include range and high input value flag in output data`
  `adc->transmit(ADS8689_WRITE_FULL,ADS8689_DATAOUT_CTL_REG,0x0500);`

Thanks!

**Comment by Helmuthn** [comment]
I'm glad you found it helpful and got it working!
